- .vscode/launch.json
- src/pandablocks_ioc/_pvi.py
- src/pandablocks_ioc/_tables.py
- src/pandablocks_ioc/ioc.py
- tests/conftest.py
This is a migration of this PR: https://github.com/PandABlocks/PandABlocks-client/pull/44
It is the initial development of PVA development.
Note that tests fail due to needing unreleased changes in PythonSoftIOC - see https://github.com/dls-controls/pythonSoftIOC/pull/102
> Structure for making a pva table

- tests/test_pvaccess.py
> Changed test to use lower case names consistent with PVA

- src/pandablocks_ioc/_hdf_ioc.py
- tests/fixtures/mocked_panda.py
- tests/test_hdf_ioc.py
Fixed the code that stops data capture once the preset maximum number of frames is collected. The HDF5 file will not contain more data points then the maximum number of frames. If the maximum number of frames is 0, then data capture continues until it is stopped.
The code was tested manually using PandABox. `PCAP` module was triggered by pulses from `CLOCK` and the number of samples (frames) to capture was set using `HDF5.NumCapture`.
> Fix: number of frames saved to HDF5

- src/pandablocks_ioc/__main__.py
- src/pandablocks_ioc/_pvi.py
- src/pandablocks_ioc/ioc.py
- tests/fixtures/mocked_panda.py
- tests/test_hdf_ioc.py
- tests/test_ioc.py
- tests/test_ioc_system.py
- tests/test_pvaccess.py
- tests/test_tables.py
- tests/test_unit_testing_structure.py
Closes #41 
I think adding a new flag as mentioned [here](https://github.com/PandABlocks/PandABlocks-ioc/pull/29#issuecomment-1708670952) could lead to some issues with pvi... We could end up with bobfiles the `screen-dir` that unintuitively  aren't actually matched to the PVs of the IOC currently running:
Running
```PandABlocks-ioc softioc 172.23.252.201 TEST-PREFIX --screens-dir=screens --skip-bobfile-en-if-dir-not-empty```
in the case where screens isn't empty and the panda has changed since the `.bob` have been created will lead to a gui that isn't necessarily up to date with the pvi of the ioc.
I think it would be cleaner to have `--overwrite-files`, but it would depend on if there's really a use case for this.
> Added new command line arguments

- pyproject.toml
- src/pandablocks_ioc/_tables.py
- tests/test_tables.py
Closes https://github.com/PandABlocks/PandABlocks-ioc/issues/16
Should only be merged after https://github.com/PandABlocks/PandABlocks-client/pull/52
> Altered code to use the new utils functions

- pyproject.toml
- src/pandablocks_ioc/_tables.py
- tests/fixtures/mocked_panda.py
- tests/fixtures/panda_data.py
- tests/test_ioc_system.py
- tests/test_tables.py
Closes #55 
Added a test to add to the panda table after initially leaving it blank
`update_table` will currently not work for enum values in the table since they're `List[str]` and have to be converted back to their integer index values.
Added a test to `update_table` for a table which is `[]` on ioc start up, then is added to on the panda side.
> Changed enum values back to uint8 before updating the table

- docs/conf.py
Explicitly changes navigation_with_keys to False
Docs CI fails because of a warning that navigation_with_keys will be defaulted to False in the next sphinx release. This prevents the warning.
> Changed `navigation_with_keys` to False

- tests/fixtures/mocked_panda.py
- tests/test_ioc_system.py
- tests/test_pvaccess.py
A couple of tests fail occasionally:
* `test_create_softioc_system` sometimes cagets `SEQ.TABLE` fields part way through the panda-side update of `SEQ.TABLE`. To fix this, the caget has been moved to the start of the test and more time has been added before `SEQ.TABLE` is updated in the mocked panda.
* `test_table_column_info` would fail because
* the test process was too fast: pva would try to fetch values before panda introspection
* the mocked panda process was too fast: by the time the pva context had been updated the mocked panda would have altered its table
* To fix the former we used a pva monitor instead of a caget, timing out at `TIMEOUT`, to fix the latter we used a different mocked panda which doesn't update its tables. We've also changed to the asyncio p4p client.
* During …
> Fixing the occasional errors in tests

- .github/workflows/code.yml
- .github/workflows/docs.yml
- pyproject.toml
Closes #68 
Pinning pvi until we update the pvi code to account for `DeviceRefs`
Also pin linter and docs CI to 3.11. We'll have to do this [unitl p4p](https://github.com/mdavidsaver/p4p/pull/126) fixes their install for 3.12. Then we can bump up our own version.
> pinned pvi version to 0.5

- tests/test-bobfiles/HDF5.bob
- tests/test-bobfiles/regenerate_test_bobfiles.py
When reverting the changes introduced from #73, The commit b5bb49bb916777bdd2cdff726ec43fd5fa422f7d includes a change to bobfiles from adding the manual flush. We have no choice but to remove it again with a new commit.
> Fixed HDF5 file

- pyproject.toml
As mentioned in #84, we should pin the pytest asyncio version.
> Pinned pytest asyncio branch

- pyproject.toml
- src/pandablocks_ioc/_pvi.py
- src/pandablocks_ioc/_tables.py
- src/pandablocks_ioc/_types.py
- tests/test-bobfiles/HDF5.bob
- tests/test-bobfiles/PCAP.bob
- tests/test-bobfiles/PULSE.bob
- tests/test-bobfiles/PandA.bob
- tests/test-bobfiles/SEQ.bob
- tests/test-bobfiles/index.bob
- tests/test_ioc_system.py
- tests/test_types.py
PVI [now uses](https://github.com/epics-containers/pvi/releases/tag/0.7) `Components` and `Widgets` which are pydantic models. The names we use in the PandA have to be adjusted to fit the schema.
Additionally I pinned PVI to 0.7.* in the pyproject.toml.
> Adjusted to use the new pydantic pvi

- src/pandablocks_ioc/ioc.py
- tests/fixtures/mocked_panda.py
- tests/test_ioc.py
This PR adds support for PV prefixes with contain `':'` (colon) characters, such as `PANDA:ES`. The existing code failed to properly handle such PVs, since the `_RecordUpdater` class was separating PV name into prefix and record name by splitting the PV name using `':'` as a separator. Changes proposed in this PR, replace splitting-based method by explicit removal of the known prefix from the PV name. The `record_prefix` is added as an attribute of the `_RecordUpdater` class.
The changes are not expected to modify the behavior of the IOC. Unit tests are modified to reflect changes in the code.
> Support for ':' (colon) characters in PV prefix

- src/pandablocks_ioc/_connection_status.py
- src/pandablocks_ioc/ioc.py
- tests/fixtures/mocked_panda.py
- tests/test_connection.py
- tests/test_ioc.py
Closes #107 
We currently cannot set the alarm state of an out record in softioc, however the new PV `PANDA:Status` will still work for our cluster liveness check.
~~We also need to make a corresponding change in the client to break out of the loop in `asyncio.AsyncioClient._ctrl_read_forever` if we receive no bytes.~~
> stopped polling for changes once the panda is in an err state

- pyproject.toml
- tests/test_hdf_ioc.py
Just a little thing pre 0.6.0 release.
> bumped up client version and added dummy `StartData` time fields in tests

- pyproject.toml
As documented in https://github.com/pytest-dev/pytest/issues/12269,
The newer release of pytest broke `pytest-asyncio==0.21.1`. There's now a new patch release of `pytest-asyncio` for those still using `0.21`.
> pinned the new release of pytest-asyncio: 0.21.2

- docs/how-to/capture-hdf.md
- src/pandablocks_ioc/_hdf_ioc.py
- tests/conftest.py
- tests/test-bobfiles/DATA.bob
- tests/test_hdf_ioc.py
Marking as draft until I can write tests and perform a full test with a real PandA system, but this works in my initial testing.
Designed to work just like the AD `CreateDirectory` system: https://github.com/areaDetector/ADCore/blob/631fb284dc06d52b9286e62418a80f7f3a7a05e2/docs/ADCore/NDPluginFile.rst?plain=1#L57-L64
The `DirectoryExists` record is also meant to behave the same as in areaDetector, and prevent attempting to write the HDF file if the target does not exist or is not writable by the user running the IOC process.
> Add two records: CreateDirectories and DirectoryExists. Automatically create directories based on this PV like in AD

- pyproject.toml
- src/pandablocks_ioc/_hdf_ioc.py
- src/pandablocks_ioc/_pvi.py
- src/pandablocks_ioc/_tables.py
- src/pandablocks_ioc/ioc.py
- tests/test_hdf_ioc.py
- tests/test_ioc.py
Closes #117
The ioc side of https://github.com/PandABlocks/PandABlocks-client/pull/91
> Add new `:DATASET` pv to capture records and pass the name to the client

- pyproject.toml
- src/pandablocks_ioc/_hdf_ioc.py
- src/pandablocks_ioc/_pvi.py
- src/pandablocks_ioc/_tables.py
- src/pandablocks_ioc/ioc.py
- tests/test_hdf_ioc.py
Adds a test to dataset name cache.
Also
* pins numpy until https://github.com/mdavidsaver/p4p/issues/145 is solved.
* adds some docstrings and comments.
* changes `:CAPTURE` to a `ComboBox` widget in the positions capture table.
> Add test to dataset name cache

- src/pandablocks_ioc/_tables.py
- src/pandablocks_ioc/ioc.py
- tests/test_tables.py
Closes https://github.com/bluesky/ophyd-async/issues/384
> fixed a race condition in the table update

- src/pandablocks_ioc/_hdf_ioc.py
- tests/test-bobfiles/DATA.bob
When testing https://github.com/bluesky/ophyd-async/pull/503 against a real PandA, I found that the PVI names for the records were not as expected. After converting to follow the other ones it works. Note the missing `_` character in the structure name, and the different format of the PV name:
```
XF:31ID1-ES{PANDA:1}:DATA:PVI structure                                         
structure record                                                            
structure _options                                                      
boolean atomic true                                                 
structure pvi                                                               
structure capture                                                       
string rw XF:31ID1-ES{PANDA:1}:DATA:CAPTURE …
```
> Edit dir creation records to standard to fix PVI output

- src/pandablocks_ioc/ioc.py
- tests/fixtures/mocked_panda.py
- tests/test_connection.py
- tests/test_ioc.py
- tests/test_ioc_system.py
Ioc side of https://github.com/PandABlocks/PandABlocks-client/pull/96, that should be merged first.
> removed min_units

- pyproject.toml
- src/pandablocks_ioc/_hdf_ioc.py
- src/pandablocks_ioc/_pvi.py
- src/pandablocks_ioc/_tables.py
- src/pandablocks_ioc/ioc.py
- tests/test-bobfiles/DATA.bob
- tests/test-bobfiles/PCAP.bob
- tests/test-bobfiles/PULSE.bob
- tests/test-bobfiles/PandA.bob
- tests/test-bobfiles/SEQ.bob
- tests/test-bobfiles/index.bob
- tests/test_ioc_system.py
> Updated PandABlocks to interface with PVI 0.10.0

- src/pandablocks_ioc/_pvi.py
- src/pandablocks_ioc/ioc.py
Closes #134 
Made the pos out calc fields (which are aliased as `:VAL`) have precision 5. Also corrected the units column in the positions table to be the correct PVs.
> 134 phoebus screen for positions makes integers

- src/pandablocks_ioc/_pvi.py
- src/pandablocks_ioc/_tables.py
> Change structure of pvi pv

- src/pandablocks_ioc/_pvi.py
For full backwards compatibility.
Will release afterwards.
> removed `"+id": "epics:nt/NTTable:1.0"`

- src/pandablocks_ioc/_pvi.py
The diff in `pvget -v PANDA1:SFP2_SYNC_IN:PVI`:
``` diff
9,11c9,11
<     time_t timeStamp 2024-11-01 15:08:17.784  
<         long secondsPastEpoch 1730473697
<         int nanoseconds 784397578
---
>     time_t timeStamp 2024-11-01 15:10:16.744  
>         long secondsPastEpoch 1730473816
>         int nanoseconds 744414767
91,108c91,106
<         structure[] bit
<             (none)
<             structure 
<                 string r PANDA1:SFP2_SYNC_IN:BIT1
<             structure 
<                 string r PANDA1:SFP2_SYNC_IN:BIT2
<             structure 
<                 string r PANDA1:SFP2_SYNC_IN:BIT3
<             structure 
<                 string r PANDA1:SFP2_SYNC_IN:BIT4
<             structure 
<                 string r PANDA1:SFP2_SYNC_IN:BIT5
<             structure 
< …
```
> stopped vectorising fields

- src/pandablocks_ioc/_pvi.py
- src/pandablocks_ioc/_tables.py
Fixes https://github.com/bluesky/ophyd-async/issues/639
> Removed access from table rows

- src/pandablocks_ioc/_hdf_ioc.py
- tests/test_hdf_ioc.py
Resolves https://github.com/bluesky/ophyd-async/issues/639
Before this change:
```
In [10]: await panda1.data.datasets.get_value()
An exception has occurred, use '%tb verbose' to see the full traceback.
ValidationError: 1 validation error for DatasetTable
type
Extra inputs are not permitted [type=extra_forbidden, input_value=['float64'], input_type=list]
For further information visit https://errors.pydantic.dev/2.9/v/extra_forbidden
See /home/xf31id/.cache/bluesky/log/bluesky.log for the full traceback.
```
After this change:
```
In [11]: await test_panda.data.datasets.get_value()
Out[11]: DatasetTable(name=[], hdf5_type=[])
In [12]: await test_panda.data.datasets.get_value()
Out[12]: DatasetTable(name=['TrigTS'], hdf5_type=[<PandaHdf5DatasetType.FLOAT_64: 'float64'>])
```
note the second …
> Use correct table col name

- src/pandablocks_ioc/_pvi.py
- src/pandablocks_ioc/ioc.py
- tests/fixtures/mocked_panda.py
- tests/test-bobfiles/SYSTEM.bob
- tests/test-bobfiles/index.bob
- tests/test_connection.py
- tests/test_ioc.py
Would be useful for checking the versions of everything on the floor without needing to get into the IOC console or logging into the IOC server.
```
(venv) [jwlodek@xf31id1-ws3 PandABlocks-ioc]$ caget TEST:PANDA_SW_VERSION 
TEST:PANDA_SW_VERSION          3.0-11-g6422090
(venv) [jwlodek@xf31id1-ws3 PandABlocks-ioc]$ caget TEST:FPGA_VERSION
TEST:FPGA_VERSION              3.0.0C4 86e5f0a2 07d202f8 
(venv) [jwlodek@xf31id1-ws3 PandABlocks-ioc]$ caget TEST:ROOTFS_VERSION
TEST:ROOTFS_VERSION            PandA 3.1a1-1-g22fdd94
(venv) [jwlodek@xf31id1-ws3 PandABlocks-ioc]$ caget TEST:VERSION
TEST:VERSION                   0.11.4.dev0+g1e1e8cd.d20241113
```
> Adding records for tracking version of IOC and PandA firmware
